[package]
name = "egui-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
egui = { version = "0.33.3", features = ["serde", "bytemuck"] }
env_logger = "0.11.8"
log = "0.4.29"
pollster = "0.4.0"
serde_json = "1.0.149"
wgpu = "28.0.0"
winit = "0.30.12"
